apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 1
  template:
    metadata:
      name: "goserver"
      labels:
        app: "goserver"
    spec:
      containers:
      - name: "goserver"
        image: "heitorpr/hello-go:v5.6"

        resources:
          requests: # -> Minimum cpu/memory to run the pod, it reserves these configurations from machine per pod
            cpu: "100m" # m -> milicores
            memory: "20Mi"
          limits:
            cpu: "500m"
            memory: "25Mi"

        startupProbe: # Ensure the initial initialization so readiness/liveness can start working together (avoid crashloopback)
          httpGet:
            path: /healthz
            port: 8000 # porta do CONTAINER
          periodSeconds: 3 # time interval between tests
          failureThreshold: 30 # how many failures to restart container
        
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 3 # time interval between tests
          failureThreshold: 1 # how many failures to restart container
          # initialDelaySeconds: 10 # when you know your application will take at least 10 seconds to start, you can start reading after 10 seconds
        
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000 # porta do CONTAINER
          periodSeconds: 5 # time interval between tests
          failureThreshold: 1 # how many failures to restart container
          timeoutSeconds: 1 # how much time to abort the request
          successThreshold: 1
          initialDelaySeconds: 15 

        envFrom:
          - configMapRef:
              name: goserver-env
          - secretRef:
              name: goserver-secret
        volumeMounts:
          - mountPath: "/go/myfamily"
            name: config
            readOnly: true
          - mountPath: "/go/pvc"
            name: goserver-pvc
      volumes:
        - name: goserver-pvc
          persistentVolumeClaim: # Give filesystem access with a persistent storage to pods
            claimName: goserver-pvc
        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: "family.txt"