apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 1
  template:
    metadata:
      name: "goserver"
      labels:
        app: "goserver"
    spec:
      containers:
      - name: "goserver"
        image: "heitorpr/hello-go:v7"
        envFrom:
          - configMapRef:
              name: goserver-env
          - secretRef:
              name: goserver-secret
        volumeMounts:
          - mountPath: "/go/myfamily"
            name: config
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: "family.txt"