apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 1
  template:
    metadata:
      name: "goserver"
      labels:
        app: "goserver"
    spec:
      containers:
      - name: "goserver"
        image: "heitorpr/hello-go:v5.5"

        startupProbe: # Ensure the initial initialization so readiness/liveness can start working together (avoid crashloopback)
          httpGet:
            path: /healthz
            port: 8000 # porta do CONTAINER
          periodSeconds: 3 # time interval between tests
          failureThreshold: 30 # how many failures to restart container
        
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 3 # time interval between tests
          failureThreshold: 1 # how many failures to restart container
          # initialDelaySeconds: 10 # when you know your application will take at least 10 seconds to start, you can start reading after 10 seconds
        
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000 # porta do CONTAINER
          periodSeconds: 5 # time interval between tests
          failureThreshold: 1 # how many failures to restart container
          timeoutSeconds: 1 # how much time to abort the request
          successThreshold: 1
          initialDelaySeconds: 15 

        envFrom:
          - configMapRef:
              name: goserver-env
          - secretRef:
              name: goserver-secret
        volumeMounts:
          - mountPath: "/go/myfamily"
            name: config
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: "family.txt"